DROP TABLE IF EXISTS clicks CASCADE;
DROP TABLE IF EXISTS urls CASCADE;

CREATE TABLE urls (
  id SERIAL PRIMARY KEY,
  shortUrl VARCHAR(255),
  longUrl VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP
);

CREATE TABLE clicks (
  urlId SERIAL REFERENCES urls(id) ON DELETE CASCADE,
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  accessed TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);